[package]
name = "euler_p091_100"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
itertools = "*"
num = "*"

[dependencies.euler_library]
git = "https://github.com/roycrippen/euler_library"
