[package]
name = "euler_p061_070"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
primal = "0.2.3"
itertools = "0.5.2"
num = "0.1.35"

[dependencies.euler_library]
git = "https://github.com/roycrippen/euler_library"
