[package]
name = "euler_p001_010"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
primal = "*"
itertools = "*"

[dependencies.euler_library]
git = "https://github.com/roycrippen/euler_library"
