[package]
name = "euler_p041_050"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
primal = "*"
permutohedron = "*"

[dependencies.euler_library]
git = "https://github.com/roycrippen/euler_library"
