[package]
name = "euler_p111_120"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
primal = "0.2.3"
num = "0.1.42"
permutohedron = "0.2.2"

[dependencies.euler_library]
path = "../euler_library"
