[package]
name = "euler_p011_020"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
itertools = "0.7.6"
num = "0.1.42"

[dependencies.euler_library]
path = "../euler_library"
