[package]
name = "euler_p081_090"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
primal = "0.2.3"
itertools = "0.7.6"
rand = "0.3.14"
numerals = "0.1.1"
petgraph = "0.4.11"

[dependencies.euler_library]
path = "../euler_library"
