[package]
name = "euler_p081_090"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
primal = "*"
itertools = "*"
rand = "*"
numerals = "*"
petgraph = "*"

[dependencies.euler_library]
git = "https://github.com/roycrippen/euler_library"
