[package]
name = "euler_p101_110"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
itertools = "0.7.6"
petgraph = "0.4.11"

[dependencies.euler_library]
path = "../euler_library"
