[package]
name = "euler_p101_110"
version = "0.1.0"
authors = ["roycrippen <roycrippen@gmail.com>"]

[dependencies]
itertools = "0.5.2"
petgraph = "0.3.2"

[dependencies.euler_library]
git = "https://github.com/roycrippen/euler_library"
